[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.100"
tokio = { version = "1.48.0", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
log = "0.4.20"
futures = "0.3.31"
quick-xml = "0.38.3"