"$schema" = "https://schema.tauri.app/config/2"
productName = "Bene Reader"
version = "0.1.0"
identifier = "com.nota.bene"

[build]
frontendDist = "../../../js/packages/bene-desktop/dist"
beforeBuildCommand = "sh -c \"cd ../../js && depot -p bene-desktop build --release\""

[[app.windows]]
title = "Bene Reader"
width = 1200
height = 900
resizable = true
fullscreen = false
titleBarStyle = "Transparent"
backgroundColor = "#F9FAF9" # should match --toolbar-bg-color

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = {"../../../js/packages/bene-reader/dist/" = "bene-reader"}

[[bundle.fileAssociations]]
ext = ["epub"]
mimeType = "application/epub+zip"
rank = "Default"